export const CHANGE = 'CHANGE';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';

export const HANDLE_ADD = 'HANDLE_ADD';
export const HANDLE_ADD_START = 'HANDLE_ADD_START';
export const HANDLE_ADD_SUCCESS = 'HANDLE_ADD_SUCCESS';
export const HANDLE_ADD_FAIL = 'HANDLE_ADD_FAIL';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const ADD_DATA = 'ADD_DATA';
export const FETCH_LIST_START = 'FETCH_LIST_START';
export const FETCH_LIST_START_SUCCESS = 'FETCH_LIST_START_SUCCESS';
export const FETCH_LIST_START_FAIL = 'FETCH_LIST_START_FAIL';

export const DELETE_DATA_START = 'DELETE_DATA_START';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAIL = 'DELETE_DATA_FAIL';

export const EDIT_DATA = 'EDIT_DATA';
export const EDIT_DATA_START = 'EDIT_DATA_START';
export const EDIT_DATA_SUCCESS = 'EDIT_DATA_SUCCESS';
export const EDIT_DATA_FAIL = 'EDIT_DATA_FAIL';

